-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    username character varying(50) NOT NULL,
    book_id integer,
    fav integer,
    reading integer,
    will_read integer,
    read integer
);

CREATE TABLE IF NOT EXISTS public.books
(
    book_id SERIAL   NOT NULL ,
    name character varying(55),
    author character varying(55),
    pages integer,
    genre character varying(55),
    quantity integer,
	borrowed integer,
    availability boolean,
    PRIMARY KEY (book_id)
);

ALTER TABLE IF EXISTS public.users
    ADD FOREIGN KEY (book_id)
    REFERENCES public.books (book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;